spring.application.name=aistudymentor
spring.datasource.url=jdbc:mysql://localhost:3306/ai_study_mentor
spring.datasource.username=springstudent
spring.datasource.password=springstudent
SECRET_KEY=${SECRET_KEY}
